name: Deploy to EC2 with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build -t girishcloudlab/my-apache-app .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image to Docker Hub
      run: |
        docker push girishcloudlab/my-apache-app:latest

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 13.201.23.43  >> ~/.ssh/known_hosts

    - name: SSH into EC2 and Deploy Docker Container
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@13.201.23.43  << EOF
        sudo docker stop apache-container || true
        sudo docker rm apache-container || true
        sudo docker pull girishcloudlab/my-apache-app:latest
        sudo docker run -d --name apache-container -p 80:80 girishcloudlab/my-apache-app:latest

       # Cleanup old Docker images
       sudo docker system prune -a -f || true
        EOF
