name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 13.201.134.207 >> ~/.ssh/known_hosts

    - name: Copy Code to EC2
      run: |
        scp -o StrictHostKeyChecking=no -r * ubuntu@13.201.134.207:/var/www/html/

    - name: Restart Apache (Optional)
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@13.201.134.207 << EOF
        sudo systemctl restart apache2
        EOF
